"""
Umlaut-Reparatur v2 — pattern-basiert mit deutscher Wortschatz-Logik.

Strategie:
1. Lade eine grosse Liste deutscher Worte mit Umlauten
2. Erzeuge für jedes Wort die ASCII-Variante (ä→ae, etc.)
3. Ersetze in Text die ASCII-Variante zurueck zum Umlaut-Wort
4. Nur exakte Wort-Matches mit Wortgrenzen (keine Teilstrings)

Vorteil: Vollständig, vermeidet False-Positives bei englischen Worten.
"""

import re
import sys
from pathlib import Path

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Umfassende Liste deutscher Worte mit Umlauten (typisch für Sachtexte).
# Statt einer Whitelist (fro→to) speichern wir nur das Ziel-Wort,
# die ASCII-Variante wird automatisch generiert.
GERMAN_UMLAUT_WORDS = set()

# === Wortstaemme + automatische Konjugations-Endungen ===
# Format: (basis-stamm-mit-umlaut, optionale-suffixe)
WORD_BASES = [
    # ä-Worte
    "Änderung", "Änderungen", "Ändern", "ändert", "änderst", "änderte", "änderten", "geändert",
    "ähnlich", "ähnliche", "ähnliches", "ähnlichen", "ähnlicher",
    "Älter", "älter", "älteste", "ältesten",
    "Anhänger", "Anhängern",
    "anfänglich", "anfängliche", "Anfänger",
    "Anlässe", "anlässlich",
    "Auffälligkeit",
    "Aufträge", "Auftrag",  # ohne Umlaut
    "ausführlich", "ausführliche", "ausführlicher",
    "auswählen", "auswählt", "ausgewählt", "auswählte",
    "befähigt", "befähigen",
    "begränzt", "begränzten",
    "begründet", "begründen", "Begründung", "Begründungen",
    "behände",
    "beiläufig",
    "benötigt", "benötigen", "benötigte",
    "berät", "beraten",  # ohne ä
    "Beschränkung",
    "Bestätigung", "bestätigt", "bestätigen",
    "betätig", "betätigt",
    "bewältigt", "bewältigen", "Bewältigung",
    "Brücke", "Brücken",
    "Bücher", "Bühne",
    "Café",
    "Charakter",  # ohne
    "Dänen", "dänisch",
    "darüber", "Daran",  # ohne
    "denkbar",
    "Dächer", "Däch",
    "drüben",
    "drücken", "drückt", "drückte",
    "dünn", "dünne",
    "ebenmäßig",
    "ehrwürdig",
    "ein­ge­hänkt",
    "einführen", "einführt", "Einführung",
    "Einschätzung", "einschätzt", "einschätzen",
    "erfreulich",
    "Erfahrungswert",
    "erfüllt", "erfüllen", "Erfüllung",
    "ergänzt", "ergänzen", "Ergänzung", "Ergänzungen",
    "Erhältlich",
    "erläutert", "erläutern", "Erläuterung",
    "erklärt", "erklären", "erklärte", "Erklärung", "Erklärungen",
    "erwähnt", "erwähnen", "Erwähnung",
    "Erläuterung", "erläutert",
    "errätselt",
    "Erörterung",
    "Erschöpfung",
    "Europäer", "europäisch", "europäische", "europäischen",
    "fähig", "Fähigkeit", "Fähigkeiten",
    "Fälle", "fällt", "Fall",  # ohne ä
    "fühlt", "fühlte", "Gefühl",
    "Führung", "führt", "führen", "geführt",
    "für", "Für",
    "geändert",
    "Gebäude", "Gebäuden",
    "gefährlich", "gefährliche", "Gefahr",  # ohne
    "geprüft",
    "gerät", "Gerät",
    "gefährdet",
    "gefördert", "fördert", "fördern", "Förderung",
    "gegründet", "gründet", "gründen", "Gründer", "Gründerin", "Gründung",
    "geöffnet", "öffnet", "öffnen", "Öffnung",
    "gestützt", "stützt", "stützen", "Stütze",
    "größer", "größte", "größten", "größeren",
    "Größe", "Größen", "groß", "großer", "großen", "großes", "großem",
    "hängt", "hängen", "Hänger",
    "hält", "halten", "halt", "hielt",  # ohne
    "Hände", "Hand",  # ohne
    "häufig", "häufige", "häufiger", "häufigsten",
    "Häuser", "Haus",  # ohne
    "Höhe", "Höhen", "höher", "höhere", "höheren",
    "Höhepunkt",
    "hörbar", "Hörbarkeit",
    "innerhalb",
    "irreführend",  # SCHWIERIG: nicht ersetzen wenn englisch
    "Jüngste", "jüngste", "jüngsten",
    "Käufer",
    "können", "könnt", "kann", "kannst", "konnten",  # ohne
    "Können",
    "Kontostände",
    "kontrolliert",
    "körperlich", "Körper", "Körpers",
    "kräftig", "kräftige", "aussagekräftig", "aussagekräftige", "aussagekräftiger",
    "Krise", "krisensicher",
    "Kunst", "künstlich", "Künste", "Künstler",
    "Künstliche", "künstliche", "künstlichen",
    "lädt", "laden",  # ohne
    "lädtbar",
    "längst", "länger", "längere", "längeren", "länger als",
    "Lärm",
    "lässt", "lässt sich",
    "Lehrbücher",
    "Leitfäden",
    "Lösung", "Lösungen", "Lösungsweg", "löst", "lösen",
    "länglich",
    "Mädchen",
    "möglich", "mögliche", "möglicher", "möglichen",
    "Möglichkeit", "Möglichkeiten",
    "mündlich",
    "müsste", "müssten", "müssen", "muss",  # ohne
    "März",
    "näher", "nächste", "nächsten", "nächstes", "nächster",
    "nämlich",
    "natürlich", "natürliche", "natürlichen",
    "nötig", "nötige",
    "nütze", "nützen", "nützlich", "nützliche",
    "Öffentlichkeit", "öffentlich", "öffentliche", "öffentlichen",
    "Öffnung",
    "Ökosystem", "ökonomisch", "Ökonomie",
    "Österreich", "österreichisch",
    "öfter",
    "Phänomen", "Phänomene", "phänomenal", "Phänomens",
    "präsentier", "Präsentation", "präsentiert",
    "prägnant",
    "präzise",
    "primär", "primären",
    "Prüfung", "prüft", "prüfen", "geprüft",
    "Qualität", "Qualitäten",
    "Quartär",
    "räumt", "räumen", "Raum",  # ohne
    "Räume", "Räumen",
    "regulär", "reguläre", "regulären",
    "reichhaltig",
    "Reihe", "Reihen",  # ohne
    "Republikaner",
    "rückläufig",
    "Rückkehr", "rückkehr", "zurückkehren",
    "Sache", "sächlich", "sächlichen",
    "schmöker",
    "schließen", "schließt", "schließe", "schloss",
    "schließlich",
    "schöpfer", "Schöpfer", "Schöpfung", "schöpferisch",
    "schräg", "schräge", "schrägen",
    "schützen", "schützt", "Schutz",  # ohne
    "schwächlich",
    "Schäden", "Schaden",  # ohne
    "schädlich", "Schädling",
    "selbstständig", "Selbstständigkeit",
    "selbständig",  # alte Rechtschreibung
    "sinngemäß",
    "Söhne", "Sohn",  # ohne
    "Sphäre",
    "spät", "später", "spätestens", "spätestes",
    "spürbar", "spürt", "spüren",
    "ständig", "Ständig",
    "Stärke", "Stärken", "stärker", "stärkste", "verstärkt",
    "stützen", "Stütze",
    "süß", "süße", "Süßigkeit",
    "Sünde",
    "tätig", "Tätigkeit", "Tätigkeiten",
    "Türen", "Tür",
    "übung", "Übungen", "üben", "übt",
    "über", "Über",
    "überall",
    "überarbeitet", "überarbeiten", "Überarbeitung",
    "Überblick",
    "übergangen",
    "übergeordnet",
    "übergibt", "übergeben",
    "überholt", "überholen",
    "überlegt", "überlegen", "Überlegung", "Überlegungen",
    "übernimmt", "übernehmen", "übernommen",
    "überprüft", "überprüfen", "Überprüfung",
    "Übersetzung",
    "Übersicht",
    "übertrieben",
    "übertroffen",
    "üblich", "übliche", "üblichen",
    "übrig", "übriges", "Übrigens",
    "umfänglich", "Umfänge",
    "Unabhängigkeit", "unabhängig",
    "Universität", "Universitäten",
    "ungefähr",
    "unmöglich",
    "Unzulässigkeit",
    "ursprünglich",
    "Verfügung", "verfügt", "verfügen", "verfügbar",
    "Vergrößerung", "vergrößern",
    "Verhältnis", "Verhältnisse",
    "verkürzt",
    "verlängert", "verlängern", "Verlängerung",
    "vermögen", "Vermögen",
    "verständlich",
    "Verständnis",
    "verstärkt", "verstärken", "Verstärkung",
    "verschmäht",
    "Versicherungs",  # ohne
    "Veränderung", "Veränderungen", "verändert", "verändern",
    "vollständig", "vollständige", "vollständiger",
    "vorgängig",
    "während",
    "Wäre", "wäre", "wären",
    "Wärme",
    "Wässer", "Wasser",  # ohne
    "Wäsche",
    "Weiß", "weiß", "weiße", "weißen", "weißer",
    "wörtlich", "wörtliche", "wörtlichen", "wörtliches",
    "Wörter", "Wort",  # ohne
    "Wünsch", "Wünsche", "wünschen", "wünscht",
    "Würde", "würde", "würden",
    "Würmer",
    "würdig",
    "Zähigkeit",
    "zählt", "zählen", "Zahl",  # ohne
    "Zähler",
    "Zukunft", "zukünftig", "zukünftige",
    "Zurückhaltung", "zurück", "zurückgehen", "zurückkehren",
    "zusätzlich", "Zusätze",
    "zuverlässig", "Zuverlässigkeit",
    "Übung", "Übungen",
    "Übernahme",
    "Übersetzer",
    "Überraschung", "überraschend", "überraschende", "überraschenden",
    "übrig",
    "äußert", "äußern", "Äußerung", "äußerst", "äußerlich",
    "ändert", "ändern", "ändernde",
    "äußere", "äußeren",
    "öl", "Öl",
    "über",
    "übermäßig",
    "übergänglich",
    "übergrößer",
    "übersehen",
    "übertragen",
    "übertreffen",
    "Übertragung",
    "Übergänge",
    "übergeben",
    "übergehen",
    "übergreifen", "übergreifend",
    "überhand",
    "überhaupt",
    "überholen", "überholt",
    "überlassen",
    "überlasten", "Überlastung",
    "überlaufen",
    "überleben", "Überlebende",
    "übermitteln", "Übermittlung",
    "übermorgen",
    "übernachten", "Übernachtung",
    "Überraschung",
    "übersetzen",
    "übersteigen",
    "überstehen",
    "überstunden",
    "übertragen",
    "überzeugen", "überzeugt", "Überzeugung",
    "überziehen",
    "übrigens",
    "übel",
    # ß-Worte
    "außen", "Außenwelt",
    "außer", "außerdem",
    "Außerordentlich",
    "befassen", "befasst",  # ohne ß
    "beißen", "beißt", "gebissen",
    "Beschäftigung",  # auch ä
    "besäße",
    "besessen",  # ohne
    "Besitz",  # ohne
    "Beweißt",  # nicht!
    "bewußt",  # alte Form
    "bloß", "bloße", "bloßen",
    "Buße",
    "draußen",
    "essen", "esse",  # ohne ß
    "Fluss", "Flüsse",
    "ganzheitlich",
    "Gemäß", "gemäß",
    "Genuss", "Genüsse",  # auch ü
    "Gewässer",
    "gewiß",  # alt
    "gewissermaßen",
    "Größe",
    "Größenordnung",
    "groß", "großer", "großen", "großes", "großem",
    "Großeltern",
    "großzügig",
    "Gruß", "Grüße",
    "gut",  # ohne
    "hieß", "hießen",
    "ineinander",
    "Kuß",  # alt
    "ließ", "ließen",
    "Lupe",  # ohne
    "Maß", "Maße", "Maßnahme",  # nicht
    "Maßnahme", "Maßnahmen",
    "muß",  # alt
    "müssen",
    "Riß",  # alt
    "schlossen", "schließen",
    "schoss",  # ohne
    "Schmuß",
    "Schoß", "schoss",
    "Spaß",
    "Süßigkeit", "süß",
    "weiße", "Weiß",
    # weitere Wichtige aus dem Bereich
    "Künstliche", "Intelligenz",  # KI selber ohne
    "länderspezifisch",
    "regelmäßig",
    "ausschließlich",
    "zugänglich",
    "Persönlichkeit", "persönlich",
    "Stärken",
    "Geschäftsmodell", "Geschäftsmodelle",
    "Wirtschaftsführer",
    "Erklärungsmodell",
    "vergrößern",
    "Tätigkeitsbereich",
    "Lebensführung",
    "Branchengröße",
    "Strömung",
    "Übersicht",
    "Übergang", "Übergänge",
    "Übersetzer",
    "Überschuss",
    "übersetzen",
    "Auslöser",
    "Ausführung",
    "Bezüglich",
    "Bedürfnis", "Bedürfnisse",
    "Behörde", "Behörden",
    "berücksichtigen", "berücksichtigt",
    "ständig", "Selbstverständnis",
    "Ähnlichkeit",
    "ähnliche",
    "Allmählich",
    "Anfänglich",
    "anhängig",
    "Aufwände",
    "ausgewählten", "ausgewählte",
    "auswählen",
    "äußerst",
    "befällt",
    "Befähigung",
    "beigefügt",
    "Beleuchtung",
    "Bemühungen", "bemüht",
    "Berufstätigkeit",
    "Beschäftigte",
    "Beschäftigung",
    "Besorgnis",
    "Besorgt",
    "besonderen",
    "Bestätigt",
    "Bewährung",
    "bewährte",
    "Beweggründe",
    "bezüglich",
    "Bezügeknoten",
    "Biervergrößerung",
    "Bürger",
    "Bürgermeister",
    "Bürgerschaft",
    "Büroangestellte",
    "Bürokratie",
    "Bürokratisch",
    "Charakterstärke",
    "Datenschutz",  # ohne
    "Datenschutzbehörde",
    "Demokratiefähigkeit",
    "Denkanstöße",
    "Drüse",
    "Druckerzeugnis",
    "durchführbar",
    "durchführen",
    "Durchführung",
    "Eigenständig", "eigenständig",
    "Einigkeit",
    "Einschränkung",
    "Eintrittsähnlich",
    "Empörung",
    "Enthülle", "enthüllt",
    "Entzündung",
    "Erbärmlich",
    "Erfahrungen",  # ohne
    "Erforderlich",
    "Ergänzungsabkommen",
    "Erhängung",
    "Erholungsphase",
    "Erinnerung",
    "Erkennbar",
    "Erkenntnisreichtum",
    "Erklärungsbedarf",
    "Erkundung",  # ohne
    "Erlebnistäuschung",
    "Erlöser",
    "Ermächtigung",
    "ermutigen",
    "ernähren",
    "Ernährung",
    "Erörterung",
    "Erscheinungen",
    "Erschöpfungszustand",
    "Erschwerung",
    "Erschütterung",
    "Erübrigt",
    "Ewigkeit",  # ohne
    "Falschmünzerei",
    "Färbung",
    "Fähigkeit",
    "Förderung",
    "Förmlich",
    "Förmlichkeit",
    "Fügung",
    "Führer", "Führers",
    "Führung",
    "Fülle",
    "Füllung",
    "Fürsorge",
    "Garstig",  # ohne
    "Geäst",
    "Gebärde",
    "Gebühr", "Gebühren",
    "Gedächtnis",
    "Gefährlich",  # = gefährlich
    "Gefährte",
    "Gegenkräfte",
    "Gegenmaßnahme",
    "Geländer",
    "Gemütlichkeit",
    "Genüge",
    "Gepäck",
    "geprägt",
    "gerade",  # ohne
    "Geräte", "Gerät",
    "geräumig",
    "Geräusche",
    "Geräuschpegel",
    "Gerüst",
    "Geschäft", "Geschäfte", "Geschäftsführer",
    "Geschmack",  # ohne
    "Geschöpf",
    "Gesellschaft",  # ohne
    "Gesetzmäßig",
    "Gesinnungsändern",
    "Gespräch", "Gespräche", "Gesprächspartner",
    "Geständnis",
    "gesund",  # ohne
    "Gewähr",
    "Gewährleistung",
    "Gewährung",
    "gewählt",
    "Gewässer",
    "geübt",
    "Gleichgängigkeit",
    "Gönnen",
    "Götter", "Gott",  # ohne
    "Größenangabe",
    "Größenordnung",
    "Größenwahn",
    "Großkraft",
    "Gründer",
    "gründlich",
    "Grünfläche",
    "Grüße",
    "gültig",
    "Gültigkeit",
    "Günstig",
    "Hähn", "Hähne",
    "Hälfte",
    "Hände",
    "Händler",
    "Hängezeit",
    "Härte",
    "Häufig",
    "Hauptdarstellerin",
    "Häuslich",
    "Heißt",  # vom hieß
    "Hervorhebung",
    "Hervorragend",
    "Höchst",
    "Höchstmaß",
    "Höflich",
    "Hörbar",
    "Hörgerät",
    "Hörsaal",
    "Hört",
    "Hülle",
    "Hülsenfrucht",
    "Hütte",
    "Übermäßig",
    "innerstaatlich",
    "Intuition",  # ohne
    "Jüngling",
    "Käfer",
    "Kämmerlein",
    "Kämpfen",
    "Kämpfer",
    "Käse",
    "kategorisch",  # ohne
    "Kläger",
    "Klärung",
    "Kläranlage",
    "klimatisch",  # ohne
    "kognitiv",  # ohne
    "Köpenick",
    "körnig",
    "Kostenträger",
    "Kostenvergrößerung",
    "Kreativität",
    "Kühlung",
    "kühnste",
    "künftig",
    "Künftige",
    "Kürze",
    "Kürzlich",
    "Kürzung",
    "Lärmschutz",
    "Lärmschwelle",
    "Längsachse",
    "Langfäuste",
    "Längere",
    "lässig",
    "Lebensglück",
    "Lebensgrundlage",  # ohne
    "Leidwesen",  # ohne
    "Leuchtend",  # ohne
    "Lückenlosigkeit",
    "Lückentext",
    "Lügen",
    "Lüger",  # nicht
    "lüstern",
    "Möbel",
    "Möglichkeit",
    "Mörder",
    "Müllabfuhr",
    "Mündung",
    "Mürbe",
    "Müßig",
    "Mütterchen",
    "Mütze",
    "Möhren",
    "Mörtel",
    "Möwe",
    "Mühe",
    "Mühlenbereich",
    "Mündig",
    "Mündigkeit",
    "Münze",
    "Nähe",
    "Näher",
    "Nährboden",
    "Nährstoff",
    "Nähung",
    "Nähverbindung",
    "Nähzeug",
    "Nährwert",
    "Nautische",
    "Nebenwirkung",  # ohne
    "Notlüge",
    "Nüsslein",
    "Oberhäuser",
    "Obhütung",
    "Ödipus",
    "Öffnen",
    "Öffnung",
    "Ökobilanz",
    "Ökologie",
    "Ökonomie",
    "Ökosystem",
    "Ökotourismus",
    "Ölbohrung",
    "Önologie",
    "Öst­erreich",
    "Pflegebedürftig",
    "Phänomen",
    "Plätze",
    "Plötzlich",
    "Plüschtier",
    "Pösel",
    "Präfix",
    "Prägung",
    "Präsenz",
    "Präzision",
    "Prinzipientreue",
    "Prinzipien",  # ohne
    "Pförtner",
    "Pünktlich",
    "Pünktlichkeit",
    "Quälerei",
    "Quälgeist",
    "Querschiff",
    "Quertreiber",
    "Räder",
    "Rätsel",
    "Räuber",
    "Rückblick",
    "Rückblicke",
    "Rückenwind",
    "Rückkehr",
    "Rückzug",
    "Rührung",
    "Rätselhaft",
    "Räumlichkeit",
    "Ränge",
    "Sänger",
    "Sängerin",
    "Sätze",
    "Säulen",
    "Säume",
    "Schöne",
    "Schönheit",
    "Schönwetter",
    "Schöpfung",
    "Schmöker",
    "Schöpfer",
    "Schmerzwürdig",  # nicht
    "Schmückung",
    "Schräg",
    "Schwächen",
    "Schwächeanfall",
    "Schwächlich",
    "Schwäger",
    "Schwägerin",
    "Schwärmer",
    "Schwärmerei",
    "Schächtelchen",
    "Schädling",
    "Schädlich",
    "Schäfer",
    "Schöpfung",
    "Schönfärberei",
    "Schöpferkraft",
    "Schönheit",
    "Schräg",
    "Schrägstellung",
    "Schwächlich",
    "Schübe",
    "Schüler",
    "Schülerin",
    "Schüssel",
    "Schütze",
    "Selbstgefälligkeit",
    "Selbstständig",
    "Selbstständigkeit",
    "Selbsttäuschung",
    "Selbstverständnis",
    "Selbstvertrauen",  # ohne
    "Sensorische",  # ohne
    "Sicherheit",  # ohne
    "Skepsis",  # ohne
    "Solidarität",
    "Sondern",  # ohne
    "Sorgfältig",
    "Souveränität",
    "Spalt",  # ohne
    "Spät",
    "Speicherbedürftig",
    "Spezifizität",
    "Spezifisch",  # ohne
    "Spielzeug",  # ohne
    "Spiritualität",
    "Sprache",  # ohne
    "Sprachgewalt",
    "Sprachvergleich",
    "Spürbar",
    "Spürhund",
    "Staatsangehörigkeit",
    "Standhaftigkeit",  # ohne
    "Ständig",
    "Stärke",
    "Stärkeprodukt",
    "Stärkung",
    "Stadtmüller",
    "Stahlträger",
    "Statthaftigkeit",
    "Stellvertretend",  # ohne
    "Stetigkeit",  # ohne
    "Stiftung",
    "Stillstehen",
    "Stimmkraft",
    "Strafmäßigkeit",
    "Streitkräfte",
    "Streitwert",  # ohne
    "Stürmen",
    "Stützen",
    "Stützpfeiler",
    "Subsidiarität",
    "Süddeutsche",
    "Süßstoff",
    "Tätig",
    "Tätigkeit",
    "Täter",
    "Tagsüber",
    "Tastatur",
    "Tasten",
    "Täuschen",
    "Teilnehmer",  # ohne
    "Teilstücke",
    "Theorie",  # ohne
    "Tiefenwirkung",
    "Topographie",  # ohne
    "Tradition",  # ohne
    "Trägerschaft",
    "Trägheit",
    "Trampolin",  # ohne
    "Traürfall",  # ohne
    "Trostlosigkeit",  # ohne
    "Trübsal",
    "Truppenstärke",
    "Tüchtigkeit",
    "Tüftelei",
    "Tüllen",
    "Türen",
    "Türkei",
    "Tüten",
    "Übel",
    "Übelkeit",
    "Übelriechen",
    "Übelwollen",
    "üben",
    "Übergänglich",
    "Übergewicht",
    "Übergreifend",
    "Überlassung",
    "Überlebt",
    "Überlegen",
    "Übernächtigt",
    "Übernahme",
    "Überprüfung",
    "Überreaktion",
    "Überreich",
    "Überschätzen",
    "Übersättigt",
    "Übersehbar",
    "Übersicht",
    "Überspannung",
    "Übersprechung",
    "Übertragung",
    "Übertreffen",
    "Übertretung",
    "Überwachung",  # nicht ä
    "Überweisung",
    "Überwiegen",
    "Überzeugung",
    "Übriges",
    "Übung",
    "Umstrukturierung",  # ohne
    "Umweltbewusstsein",  # ohne
    "Unangenehmes",  # ohne
    "Unangetastet",  # ohne
    "Unauffällig",
    "Unausführbar",
    "Unbeständig",
    "Unberührtheit",
    "Undurchsichtig",  # ohne
    "Unentbehrlich",  # ohne
    "Unentwegt",
    "Unerlässlich",
    "Unfähig",
    "Unförmig",
    "Ungebunden",  # ohne
    "Ungefähr",
    "Ungleichgewicht",  # ohne
    "Ungültig",
    "Unhöflich",
    "Universität",
    "Unkenntlich",
    "Unleserlich",
    "Unmöglich",
    "Unmündig",
    "Unmäßig",
    "Unnötig",
    "Unparteiisch",  # ohne
    "Unpassend",  # ohne
    "Unpünktlich",
    "Unrentabel",  # ohne
    "Unschätzbar",
    "Unschön",
    "Unsicherheit",  # ohne
    "Unsterblich",  # ohne
    "Unstetig",  # ohne
    "Unstetigkeit",  # ohne
    "Unsterbliche",  # ohne
    "Untauglich",  # ohne
    "Untergäre",  # ohne
    "Unterbrechung",  # ohne
    "Unterdrückung",
    "Untergröße",
    "Unterhöhlung",
    "Untertänigkeit",
    "Unverhältnismäßig",
    "Unverwöhnt",
    "Unwürdig",
    "Unzulässig",
    "Unzulänglichkeit",
    "Unzuverlässigkeit",
    "Vergänglich",
    "Vergänglichkeit",
    "Vergüns",  # nicht
    "Vergütung",
    "Verhältnis",
    "Verhältnisschmerz",
    "Verhärtung",
    "Verhüllung",
    "Verkäufer",
    "Verkürzung",
    "Verlängerungskabel",
    "Verlässlich",
    "Verlässlichkeit",
    "Vermächtnis",
    "Verminderung",
    "Vermögensverwalter",
    "Vermöglich",
    "Vernünftig",
    "Vernünftigkeit",
    "Verprügeln",
    "Verspätung",
    "Verständigung",
    "Verständigungswurzel",
    "Verständnis",
    "verstärken",
    "Verstärkung",
    "Verstörung",
    "Versöhnung",
    "Vertäuung",
    "Vertrauensbrücke",
    "Vergrößerung",
    "Vergrößerungsglas",
    "Verzärtelung",
    "Vorbildlich",  # ohne
    "Vorratshäuser",
    "Vorständen",  # ohne
    "Vorzüglich",
    "Wächter",
    "Wänder",
    "Wäre",
    "Wärmflasche",
    "Wäscherei",
    "Während",
    "Wässerchen",
    "Weiß",
    "Wechselbeziehung",  # ohne
    "Weiß",
    "Weißbier",
    "Weißbrot",
    "Wert",  # ohne
    "Wesensänderung",
    "Wesensgrundlage",
    "Wiederholung",  # ohne
    "Wiederversöhnung",
    "Wirklichkeit",  # ohne
    "Wissensänderung",
    "Wissensgrundlage",
    "Wohlstandsmüll",
    "Wohltäter",
    "Wölbung",
    "Wörter",
    "Wörtlich",
    "Würde",
    "Würmer",
    "Würzburg",
    "Würzschnitten",
    "Zähneknirschen",
    "Zähigkeit",
    "Zähne",
    "Zähren",
    "Zänkerei",
    "Zärtlich",
    "Zärtlichkeit",
    "Zäume",
    "Zentralität",  # ohne
    "Zensur",  # ohne
    "Zerklüftet",
    "Zerstörung",
    "Zerstreuung",  # ohne
    "Zerstückelung",
    "Zerwürfnis",
    "Zeugnis",
    "Zollbestände",
    "Zugänglichkeit",
    "Zugänge",
    "Zuhälter",
    "Zukunft",
    "Zukünftig",
    "Zumutbarkeit",
    "Zünder",
    "Zünden",
    "Zündkerze",
    "Zünftig",
    "Zünglein",
    "Zurückgekehrt",
    "Zurückhaltung",
    "Zurückreichen",
    "Zusätzlich",
    "Zustände",
    "Zustand",  # ohne
    "Zuverlässigkeit",
    "Zwischenwesen",  # ohne
    "Zynisch",  # ohne
    # Anwendungs-spezifisch
    "Verständnis", "Verständnis",  # mein verstandnis fixt
    "verändert",
    "Wesensverschiebung",
    "Spürbar",
    "Sprache",  # ohne
    "Räderwerk",
    "Räderwerkfehler",
    "Schaltkreis",  # ohne
    "Schädlich",
    "Schäden",
    "Schmerzgefühl",
    "Schöpfungsakt",
    "Schwesterfirma",  # ohne
    "Selbständig",
    "Skrupellosigkeit",  # ohne
    "Spätfolgen",
    "Sportbegabung",  # ohne
    "Sprache",  # ohne
    "Springvermögen",
    "Standfähigkeit",
    "Stärkebrand",
    "Strebsamkeit",  # ohne
    "Übergang",
    "Übergangszeit",
    "Übergewichtig",
    "Überheblichkeit",
    "Überhöhung",
    "Überschuss",
    "Überschuss­bilanz",
    "Übersetzungsschnitten",
    "Übersicht",
    "Überstellungsverhandlung",
    "Überwachung",
    "Übertragung",
    "Überzeugung",
    "Üblich",
    "Übungsbedarf",
    "Übungsplatz",
    "Übungsplatztechnik",
    "Übungsvorgang",
    "öffentliche",
    "öffnen",
    "Älterer",
    "Ältester",
    "Ärger",
    "ärgerlich",
    "Ärgernisses",
    "Ärgerlich",
    # zusätzliche aus den Sektionen typisch
    "geändert",
    "geöffnet",
    "geprüft",
    "geschäftlich",
    "Geschäfte",
    "größer",
    "hängt",
    "hätte",
    "hätten",
    "irrelevant",  # ohne
    "können",  # ohne
    "Kontextüberhang",
    "Lösungsweg",
    "März",
    "müssen",
    "öffentlich",
    "präsentieren",
    "präzise",
    "räumlich",
    "stört",
    "stören",
    "Strömungen",
    "über",
    "übergeht",
    "übergeordnet",
    "überholt",
    "überlegt",
    "übernommen",
    "überprüft",
    "übersieht",
    "übertroffen",
    "üblich",
    "üblicherweise",
    "übrig",
    "übrigens",
    "Übung",
    "während",
    "wählerisch",
    "Wörter",
    "Würde",
    "Größe",
    "spürbar",
    "Verständnis",
    "Bewährungshelfer",
    "Wirtschaftsführer",
    "Geschäftsbericht",
    "Geschäftsmodell",
    "Geschäftsmodelle",
    "Geschäftspartner",
    "Geschäftsumfeld",
    "Geschäftsumsatz",
    "Geschäftswelt",
    "Gewährträger",
    "Mitgründer",  # WICHTIG
    "Mitbegründer",
    "Mitschöpfer",
    "Mitläufer",
    # Spezifisch aus 2.1 Beobachtungen
    "Mitgründer",  # vorher Mitgründer
    "Verständnis",  # Verständnis
    "später",  # später
    "März",  # März
    "plötzlich",  # plötzlich
    "hält",  # hält
    "ergänzt",  # ergänzt
    "Präsentation",  # Präsentation
    "Einschätzung",  # Einschätzung
    "lässt",  # lässt
    "Vorgänge",  # Vorgänge
    "länger",  # länger
    "Phänomen",  # Phänomen
    "Stärke",  # Stärke
    "Gerüst",  # Gerüst
    "stärker",  # stärker
    "irreführend",  # irreführend
    "heißt",  # heißt
    "Gründer",  # Gründer
    "Wahrnehmung",  # ohne
    "fähig",
    "Fähigkeiten",
    "öfter",
    "öffnet",
    "schließlich",
    "übrigens",
    "Wertschöpfungs",
    "Geschäftsanwender",
    "Wesensverschiebung",
    "größtenteils",
    "geprüft",
    "verschöbe",
    "wäre",
    "äh",
    "öh",
    "ähm",
]

# Build replacement map
def asciify(word: str) -> str:
    return (word.replace("ä", "ae").replace("ö", "oe").replace("ü", "ue")
            .replace("Ä", "Ae").replace("Ö", "Oe").replace("Ü", "Ue")
            .replace("ß", "ss"))

REPLACEMENTS = {}
for word in WORD_BASES:
    ascii_form = asciify(word)
    if ascii_form != word:  # Wort enthält Umlaute
        # Nur ersetzen wenn Konflikt unwahrscheinlich
        if ascii_form not in REPLACEMENTS:
            REPLACEMENTS[ascii_form] = word

# Speziell GEFÄHRLICHE englische Worte, die NICHT konvertiert werden dürfen
ENGLISH_BLOCKLIST = {
    "Sue", "queue", "Lue", "Used", "uses", "user", "Users", "useful",
    "Goethe", "Boeing", "see", "tree", "Lee", "fee",
    "doesnt", "doesn", "Goal", "goal", "Goals",
    "open", "Open", "OpenAI", "openai", "OpenClaw",
    "Note", "note", "boost", "Boost",
    "Tool", "tool", "Tools", "tools", "stool",
    "Boot", "boot", "Boots",
    "Loop", "loop", "Loops", "loops",
    "Cool", "cool", "schoell",  # bewusst kein Umlaut
    "Look", "look",
    "Spoon", "spoon",
    "Moon", "moon",
    "Soon", "soon",
    "Stoop", "stoop",
    "Goose", "goose",
    "True", "true",
    "Blue", "blue",
    "Clue", "clue",
    "Glue", "glue",
    "Pueblo",
    "Tue", "Tuesday",
    "Tuesday",
    "Suess",
    "Sue", "Suess",
    "Lueder",  # name
    "Schmidt", "Mueller", "Mueller",  # auch Namen!
    "Schmitt",
    "Strauss",  # Eigenname
    "Mannheim",
    "Heidelberg",
    "fully", "really", "see", "team", "Team",
    "GmbH",
    "Co",  # nicht
    "AGB",  # nicht
    "URL", "URLs",
    "HTTP", "HTTPS",
    "API", "APIs",
    "JSON", "XML", "HTML", "CSS",
}

# Sonderfaelle: oft schwierige Worte
SPECIAL_REPLACEMENTS = [
    # (ASCII-Pattern, Umlaut-Variante) — wird mit Wortgrenzen ersetzt
    ("März", "März"),
    ("Verständnis", "Verständnis"),
    ("später", "später"),
    ("plötzlich", "plötzlich"),
    ("hält", "hält"),
    ("ergänzt", "ergänzt"),
    ("Präsentation", "Präsentation"),
    ("Einschätzung", "Einschätzung"),
    ("lässt", "lässt"),
    ("Vorgänge", "Vorgänge"),
    ("länger", "länger"),
    ("Phänomen", "Phänomen"),
    ("Stärke", "Stärke"),
    ("Gerüst", "Gerüst"),
    ("stärker", "stärker"),
    ("irreführend", "irreführend"),
    ("heißt", "heißt"),
    ("Gründer", "Gründer"),
    ("Mitgründer", "Mitgründer"),
    ("Wesensverschiebung", "Wesensverschiebung"),
    ("verschöbe", "verschöbe"),
    ("Präsidenten", "Präsidenten"),
    ("Präsident", "Präsident"),
    ("erklärt", "erklärt"),
    ("Erklärung", "Erklärung"),
    ("erkläre", "erkläre"),
    ("während", "während"),
    ("Während", "Während"),
    ("hervorgehoben", "hervorgehoben"),
    ("übrig", "übrig"),
    ("übung", "übung"),
    ("Übung", "Übung"),
    ("auswähl", "auswähl"),
    ("Auswähl", "Auswähl"),
    ("wähl", "wähl"),
    ("Wähl", "Wähl"),
    ("über", "über"),
    ("Über", "Über"),
    ("über", "über"),
    ("für", "für"),
    ("Für", "Für"),
    ("müssen", "müssen"),
    ("Müssen", "Müssen"),
    ("natürlich", "natürlich"),
    ("Natürlich", "Natürlich"),
    ("natürlich", "natürlich"),
    ("Tür", "Tür"),
    ("tür", "tür"),
    ("wäre", "wäre"),
    ("Wäre", "Wäre"),
    ("wären", "wären"),
    ("Wären", "Wären"),
    ("hätte", "hätte"),
    ("Hätte", "Hätte"),
    ("hätten", "hätten"),
    ("Hätten", "Hätten"),
    ("Verlängerung", "Verlängerung"),
    ("verlängert", "verlängert"),
    ("Förderung", "Förderung"),
    ("förder", "förder"),
    ("Förder", "Förder"),
    ("Lösung", "Lösung"),
    ("Lösungen", "Lösungen"),
    ("löse", "löse"),
    ("Löse", "Löse"),
    ("lösch", "lösch"),
    ("Lösch", "Lösch"),
    ("Begründung", "Begründung"),
    ("begründ", "begründ"),
    ("Begründ", "Begründ"),
    ("benötig", "benötig"),
    ("Benötig", "Benötig"),
    ("ausgewähl", "ausgewähl"),
    ("Ausgewähl", "Ausgewähl"),
    ("Fähigkeit", "Fähigkeit"),
    ("fähigkeit", "fähigkeit"),
    ("Fähig", "Fähig"),
    ("fähig", "fähig"),
    ("nächst", "nächst"),
    ("Nächst", "Nächst"),
    ("nächste", "nächste"),
    ("Nächste", "Nächste"),
    ("Fälle", "Fälle"),
    ("Fall", "Fall"),  # kein Umlaut
    ("höh", "höh"),
    ("Höh", "Höh"),
    ("höher", "höher"),
    ("Höher", "Höher"),
    ("Höhe", "Höhe"),
    ("höhe", "höhe"),
    ("Größ", "Größ"),
    ("größ", "größ"),
    ("Größe", "Größe"),
    ("größe", "größe"),
    ("Größer", "Größer"),
    ("größer", "größer"),
    ("häufig", "häufig"),
    ("Häufig", "Häufig"),
    ("regelmäßig", "regelmäßig"),
    ("Regelmäßig", "Regelmäßig"),
    ("sinngemäß", "sinngemäß"),
    ("Sinngemäß", "Sinngemäß"),
    ("zugänglich", "zugänglich"),
    ("Zugänglich", "Zugänglich"),
    ("Männlich", "Männlich"),
    ("männlich", "männlich"),
    ("Weiblich", "Weiblich"),  # kein
    ("präzis", "präzis"),
    ("Präzis", "Präzis"),
    ("prägend", "prägend"),
    ("Prägend", "Prägend"),
    ("prägt", "prägt"),
    ("Prägt", "Prägt"),
    ("prägen", "prägen"),
    ("Prägen", "Prägen"),
    ("regulär", "regulär"),
    ("Regulär", "Regulär"),
    ("primär", "primär"),
    ("Primär", "Primär"),
    ("sekundär", "sekundär"),
    ("Sekundär", "Sekundär"),
    ("Behörde", "Behörde"),
    ("behörd", "behörd"),
    ("vollständig", "vollständig"),
    ("Vollständig", "Vollständig"),
    ("kräftig", "kräftig"),
    ("Kräftig", "Kräftig"),
    ("aussagekräftig", "aussagekräftig"),
    ("ungefähr", "ungefähr"),
    ("Ungefähr", "Ungefähr"),
    ("Außerdem", "Außerdem"),
    ("außerdem", "außerdem"),
    ("Außer", "Außer"),
    ("außer", "außer"),
    ("außerordentlich", "außerordentlich"),
    ("Außerordentlich", "Außerordentlich"),
    ("Anlässe", "Anlässe"),
    ("anlässe", "anlässe"),
    ("anlässlich", "anlässlich"),
    ("Anlässlich", "Anlässlich"),
    ("schließlich", "schließlich"),
    ("Schließlich", "Schließlich"),
    ("schließ", "schließ"),
    ("Schließ", "Schließ"),
    ("ließ", "ließ"),
    ("Ließ", "Ließ"),
    ("hieß", "hieß"),
    ("Hieß", "Hieß"),
    ("Straße", "Straße"),
    ("straße", "straße"),
    ("weiß", "weiß"),
    ("Weiß", "Weiß"),
    ("Erfahrung", "Erfahrung"),  # ohne!
    ("Vorläufig", "Vorläufig"),
    ("vorläufig", "vorläufig"),
    ("hätscheln", "hätscheln"),
    ("Hätscheln", "Hätscheln"),
    ("zuverlässig", "zuverlässig"),
    ("Zuverlässig", "Zuverlässig"),
    ("unzuverlässig", "unzuverlässig"),
    ("Unzuverlässig", "Unzuverlässig"),
    ("Allmählich", "Allmählich"),
    ("allmählich", "allmählich"),
    ("Auffällig", "Auffällig"),
    ("auffällig", "auffällig"),
    ("Maßnahm", "Maßnahm"),
    ("maßnahm", "maßnahm"),
    ("Spaß", "Spaß"),
    ("spaß", "spaß"),
    ("Groß", "Groß"),
    ("groß", "groß"),
    ("Erwähnt", "Erwähnt"),
    ("erwähnt", "erwähnt"),
    ("erwähn", "erwähn"),
    ("Erwähn", "Erwähn"),
    ("wählen", "wählen"),
    ("Wählen", "Wählen"),
    ("wähl", "wähl"),
    ("Wähl", "Wähl"),
    ("Bevölker", "Bevölker"),
    ("bevölker", "bevölker"),
    ("öffn", "öffn"),
    ("Öffn", "Öffn"),
    ("Öffn", "Öffn"),  # weiter
    ("öffentlich", "öffentlich"),
    ("Öffentlich", "Öffentlich"),
    ("öffentlichkeit", "öffentlichkeit"),
    ("Öffentlichkeit", "Öffentlichkeit"),
    ("hervorgehoben", "hervorgehoben"),
    ("Veröffentlich", "Veröffentlich"),
    ("veröffentlich", "veröffentlich"),
    ("Veröffentlichung", "Veröffentlichung"),
    ("veröffentlichung", "veröffentlichung"),
    ("eröffnen", "eröffnen"),
    ("Eröffnen", "Eröffnen"),
    ("erfahrungs", "erfahrungs"),  # ohne
    ("Erfahrungs", "Erfahrungs"),
    # zusätzliche aus Inspektion 2.1
    ("aufruckt", "aufruckt"),  # nein, aufruckt stimmt nicht
    ("Schlüssel", "Schlüssel"),
    ("schlüssel", "schlüssel"),
    ("Geheimnis", "Geheimnis"),  # ohne
    ("Werkstücke", "Werkstücke"),
    ("werkstück", "werkstück"),
    ("Werkstück", "Werkstück"),
    # Composite-Worte typisch
    ("änderung", "änderung"),
    ("Änderung", "Änderung"),
    ("Anwendungsfälle", "Anwendungsfälle"),
    ("anwendungsfälle", "anwendungsfälle"),
    ("Spätestens", "Spätestens"),
    ("spätestens", "spätestens"),
    ("Tatsächlich", "Tatsächlich"),
    ("tatsächlich", "tatsächlich"),
    ("Wesentlich", "Wesentlich"),  # ohne
    ("Wirklich", "Wirklich"),  # ohne
    ("schädlich", "schädlich"),
    ("Schädlich", "Schädlich"),
    ("Schaden", "Schaden"),  # ohne
    ("Aktualisier", "Aktualisier"),  # ohne (englischer Stamm)
    ("aktualisier", "aktualisier"),
    ("Verändert", "Verändert"),
    ("Verändert", "Verändert"),
    ("verändert", "verändert"),
    ("Veränder", "Veränder"),
    ("veränder", "veränder"),
    ("Verselbständigung", "Verselbständigung"),
    ("verselbständigung", "verselbständigung"),
    ("erkundungs", "erkundungs"),  # ohne
    ("erwarten", "erwarten"),  # ohne
    ("Erweiterte", "Erweiterte"),  # ohne
    ("Hinzufügung", "Hinzufügung"),
    ("hinzufügung", "hinzufügung"),
    ("Hinzufüg", "Hinzufüg"),
    ("hinzufüg", "hinzufüg"),
    ("Ausführung", "Ausführung"),
    ("ausführung", "ausführung"),
    ("Ausführ", "Ausführ"),
    ("ausführ", "ausführ"),
    ("Berücksichtigung", "Berücksichtigung"),
    ("berücksichtig", "berücksichtig"),
    ("Berücksichtig", "Berücksichtig"),
    ("durchgängig", "durchgängig"),
    ("Durchgängig", "Durchgängig"),
    ("vorläufig", "vorläufig"),
    ("Vorläufig", "Vorläufig"),
    ("Eingrenzung", "Eingrenzung"),  # ohne
    ("Eindruck", "Eindruck"),  # ohne
    ("Eintragung", "Eintragung"),  # ohne
    ("Inhaltlich", "Inhaltlich"),  # ohne
    ("International", "International"),  # nein,
    ("Internat", "Internat"),  # ohne
    ("Akademie", "Akademie"),  # ohne
    ("Präzisierung", "Präzisierung"),
    ("präzisierung", "präzisierung"),
    ("Präzise", "Präzise"),
    ("präzise", "präzise"),
    ("Präzi", "Präzi"),
    ("präzi", "präzi"),
    ("Inkraftsetzung", "Inkraftsetzung"),  # ohne
    ("Bezügen", "Bezügen"),
    ("bezügen", "bezügen"),
    ("Bezug", "Bezug"),  # ohne
    ("zusätzliche", "zusätzliche"),
    ("Zusätzliche", "Zusätzliche"),
    ("zusätzlich", "zusätzlich"),
    ("Zusätzlich", "Zusätzlich"),
    ("nachträglich", "nachträglich"),
    ("Nachträglich", "Nachträglich"),
    ("Männlich", "Männlich"),
    ("männlich", "männlich"),
    ("Geschlechtlich", "Geschlechtlich"),  # ohne
    ("übersetz", "übersetz"),
    ("Übersetz", "Übersetz"),
    ("Versuchung", "Versuchung"),  # ohne ü
    ("Versuchung", "Versuchung"),  # ohne
    ("Lehrwerk", "Lehrwerk"),  # ohne
    ("Lehrwerke", "Lehrwerke"),
    # spez für 2.1 entdeckt
    ("aufzähl", "aufzähl"),
    ("Aufzähl", "Aufzähl"),
    ("aufzählen", "aufzählen"),
    ("Aufzählung", "Aufzählung"),
    ("nächsten", "nächsten"),
    ("Nächsten", "Nächsten"),
    ("übersichtlich", "übersichtlich"),
    ("Übersichtlich", "Übersichtlich"),
    ("Geschwindigkeit", "Geschwindigkeit"),  # ohne
    ("Veränderungen", "Veränderungen"),
    ("veränderungen", "veränderungen"),
    ("Veränderung", "Veränderung"),
    ("veränderung", "veränderung"),
]

# Dateien die wir behandeln
def should_process(path: Path) -> bool:
    if any(part in {"node_modules", "audio_cache", "thumbnails", "_briefings", "__pycache__", "test_screenshots", ".git"} for part in path.parts):
        return False
    if path.suffix not in {".md", ".py", ".js", ".html", ".css", ".json"}:
        return False
    if path.suffix == ".json":
        return path.name in {"_book.json", "_index.json", "channel.config.json"}
    return True


# Substring-Patterns für deutsche Komposita
# Diese werden auch INNERHALB eines Wortes ersetzt
COMPOSITE_SUBSTRINGS = [
    ("führ", "führ"),   # durchführen, vorführen, einführen, etc.
    ("Führ", "Führ"),
    ("schöpf", "schöpf"),
    ("Schöpf", "Schöpf"),
    ("präsent", "präsent"),
    ("Präsent", "Präsent"),
    ("präsid", "präsid"),
    ("Präsid", "Präsid"),
    ("kompat", "kompat"),  # bleibt!
    ("anfäng", "anfäng"),
    ("Anfäng", "Anfäng"),
    ("Kompatibilität", "Kompatibilität"),
    ("kompatibilität", "kompatibilität"),
    ("Produktivität", "Produktivität"),
    ("produktivität", "produktivität"),
    ("Wertschöpfung", "Wertschöpfung"),
    ("wertschöpfung", "wertschöpfung"),
    ("Wertschöpfungs", "Wertschöpfungs"),
    ("wertschöpfungs", "wertschöpfungs"),
    ("vität", "vität"),  # alle -vität worte
    ("Vität", "Vität"),
    ("stärk", "stärk"),
    ("Stärk", "Stärk"),
    ("trägt", "trägt"),
    ("Trägt", "Trägt"),
    ("träg", "träg"),  # Vorsicht: nur als Substring innerhalb deutscher Worte
    ("Träg", "Träg"),
    ("äner", "äner"),  # für Anwender, Säuren, Männer
    ("Äner", "Äner"),
    ("ömarkt", "ömarkt"),
    ("äkult", "äkult"),
    ("äkultur", "äkultur"),
    ("ökonom", "ökonom"),
    ("Ökonom", "Ökonom"),
    ("äglich", "äglich"),
    ("Äglich", "Äglich"),
    ("ürlich", "ürlich"),
    ("Ürlich", "Ürlich"),
    ("zähl", "zähl"),
    ("Zähl", "Zähl"),
    ("hervorgehoben", "hervorgehoben"),
    ("änge", "änge"),  # Anhänge, Vorgänge
    ("Änge", "Änge"),
    ("örter", "örter"),
    ("Örter", "Örter"),
    ("übung", "übung"),
    ("Übung", "Übung"),
    ("üblich", "üblich"),
    ("Üblich", "Üblich"),
    ("ängt", "ängt"),  # hängt, prangt nicht
    ("Ängt", "Ängt"),
    ("ält", "ält"),
    ("Ält", "Ält"),
    ("änz", "änz"),  # ergänzt, distanzieren nicht
    ("Änz", "Änz"),
    ("änd", "änd"),  # Änderung, Stände, Hände, Bestände
    ("Änd", "Änd"),
    ("ödl", "ödl"),  # Lödl nicht, Ödland ja
    ("üle", "üle"),  # nicht
    ("änkt", "änkt"),
    ("Änkt", "Änkt"),
    ("änz", "änz"),
    ("Änz", "Änz"),
    ("äbt", "äbt"),
    ("Äbt", "Äbt"),
    ("äuten", "äuten"),  # nicht hilfreich
    ("öhe", "öhe"),  # Höhe, nicht "Goethe" da Eigenname
    ("Öhe", "Öhe"),
    ("äufig", "äufig"),  # häufig, nicht "queueig"
    ("Äufig", "Äufig"),
    ("üft", "üft"),  # geprüft, nicht "scoutet"
    ("Üft", "Üft"),
    ("üllt", "üllt"),
    ("Üllt", "Üllt"),
    ("ürd", "ürd"),  # würde, nicht "Lord"
    ("Ürd", "Ürd"),
    ("ürz", "ürz"),  # Würzburg, kürzlich
    ("Ürz", "Ürz"),
    ("ärf", "ärf"),  # darf
    ("Ärf", "Ärf"),
    ("ärm", "ärm"),  # Lärm, Wärme
    ("Ärm", "Ärm"),
    ("ärb", "ärb"),  # Färbung, Erwerb nicht
    ("Ärb", "Ärb"),
    ("ürl", "ürl"),  # natürlich, gewürzt
    ("Ürl", "Ürl"),
    ("ätig", "ätig"),  # tätig
    ("Ätig", "Ätig"),
    ("üfel", "üfel"),
    ("Üfel", "Üfel"),
    ("ärung", "ärung"),  # Erklärung, Verschärfung, Bewährung
    ("Ärung", "Ärung"),
    ("örlich", "örlich"),
    ("Örlich", "Örlich"),
    ("örper", "örper"),  # Körper
    ("Örper", "Örper"),
    ("önnen", "önnen"),  # können, gönnen
    ("Önnen", "Önnen"),
    ("ürnt", "ürnt"),
    ("Ürnt", "Ürnt"),
    ("ürf", "ürf"),  # würfeln, dürfen
    ("Ürf", "Ürf"),
    ("üllen", "üllen"),  # füllen, hüllen
    ("Üllen", "Üllen"),
    ("ösen", "ösen"),  # lösen, böse
    ("Ösen", "Ösen"),
    ("öst", "öst"),
    ("Öst", "Öst"),
    ("örter", "örter"),  # Wörter
    ("Örter", "Örter"),
    ("üssen", "üssen"),  # müssen, küssen
    ("Üssen", "Üssen"),
    ("üsst", "üsst"),
    ("Üsst", "Üsst"),
    ("öglich", "öglich"),  # möglich
    ("Öglich", "Öglich"),
    ("äge", "äge"),  # Säge, Träger, Anhänge
    ("Äge", "Äge"),
    ("ühr", "ühr"),  # führen, Wahrnehmung nicht (kein ue da)
    ("Ühr", "Ühr"),
    ("übung", "übung"),
    ("Übung", "Übung"),
    ("uberg", "uberg"),  # nicht
]

EXTRA_COMPOSITES = [
    # Häufige Komposita explizit (ohne Risiko)
    ("durchführen", "durchführen"),
    ("durchgeführt", "durchgeführt"),
    ("ausführen", "ausführen"),
    ("ausgeführt", "ausgeführt"),
    ("vorgeführt", "vorgeführt"),
    ("vorführt", "vorführt"),
    ("einführen", "einführen"),
    ("eingeführt", "eingeführt"),
    ("Einführung", "Einführung"),
    ("Anfänger", "Anfänger"),
    ("anfänger", "anfänger"),
    ("Kompatibilität", "Kompatibilität"),
    ("kompatibilität", "kompatibilität"),
    ("Produktivität", "Produktivität"),
    ("produktivität", "produktivität"),
    ("Produktivitätssteigerung", "Produktivitätssteigerung"),
    ("Wertschöpfung", "Wertschöpfung"),
    ("wertschöpfung", "wertschöpfung"),
    ("Wertschöpfungsklasse", "Wertschöpfungsklasse"),
    ("Wertschöpfungskette", "Wertschöpfungskette"),
    ("Kundenpräsentation", "Kundenpräsentation"),
    ("kundenpräsentation", "kundenpräsentation"),
    ("Eigenständig", "Eigenständig"),
    ("eigenständig", "eigenständig"),
    ("Universität", "Universität"),
    ("universität", "universität"),
    ("Universitäten", "Universitäten"),
    ("Realität", "Realität"),
    ("realität", "realität"),
    ("Fähigkeiten", "Fähigkeiten"),
    ("fähigkeiten", "fähigkeiten"),
    ("Lebensläufe", "Lebensläufe"),
    ("Werkstücke", "Werkstücke"),
    ("Werkstück", "Werkstück"),
    ("Bemühungen", "Bemühungen"),
    ("Berücksichtigung", "Berücksichtigung"),
    ("Komplexität", "Komplexität"),
    ("Verfügbarkeit", "Verfügbarkeit"),
    ("zurückgehen", "zurückgehen"),
    ("zurückgekehrt", "zurückgekehrt"),
    ("zurückhaltend", "zurückhaltend"),
    ("Überbringung", "Überbringung"),
    ("Übertragung", "Übertragung"),
    ("übertragen", "übertragen"),
    ("Überlegung", "Überlegung"),
    ("überlegen", "überlegen"),
    ("Überraschung", "Überraschung"),
    ("überraschend", "überraschend"),
    ("überraschende", "überraschende"),
    ("Voraussichtlich", "Voraussichtlich"),  # typo
    ("voraussichtlich", "voraussichtlich"),
    ("Tagesaktualität", "Tagesaktualität"),
    ("Aktualität", "Aktualität"),
    ("Funktionalität", "Funktionalität"),
    ("Effizienz", "Effizienz"),  # nope
    ("Spezialität", "Spezialität"),
    ("Identität", "Identität"),
    ("Stabilität", "Stabilität"),
    ("Verfügbarkeit", "Verfügbarkeit"),
    ("Mehrwert", "Mehrwert"),  # ohne
    ("Geschwindigkeit", "Geschwindigkeit"),  # ohne
    ("überholt", "überholt"),
    ("Überholt", "Überholt"),
    ("Lehrbücher", "Lehrbücher"),
    ("Verfügung", "Verfügung"),
    ("verfügung", "verfügung"),
    ("überzeugt", "überzeugt"),
    ("Überzeugt", "Überzeugt"),
    ("überzeugen", "überzeugen"),
    ("Überzeugen", "Überzeugen"),
    ("Überzeugung", "Überzeugung"),
    ("überzeugung", "überzeugung"),
    ("überlegt", "überlegt"),
    ("Überlegt", "Überlegt"),
    ("Erfüll", "Erfüll"),
    ("erfüll", "erfüll"),
    ("Schlüssel", "Schlüssel"),
    ("schlüssel", "schlüssel"),
    ("Schluss-Sätze", "Schluss-Sätze"),
    ("Vorgängig", "Vorgängig"),
    ("vorgängig", "vorgängig"),
    ("Vorgangsweise", "Vorgangsweise"),  # ohne
    ("Maßnahmen", "Maßnahmen"),
    ("maßnahmen", "maßnahmen"),
    ("Maßnahme", "Maßnahme"),
    ("maßnahme", "maßnahme"),
    ("Bewusstseinszustand", "Bewusstseinszustand"),  # ohne ü, kein
    ("Eindrücke", "Eindrücke"),
    ("eindrücke", "eindrücke"),
    ("Verständnis", "Verständnis"),  # nochmal
    ("verständnis", "verständnis"),
    ("Selbstverständnis", "Selbstverständnis"),
    ("Empfänger", "Empfänger"),
    ("empfänger", "empfänger"),
    ("Verfälschung", "Verfälschung"),
    ("Verfälsch", "Verfälsch"),
    ("Modelle", "Modelle"),  # ohne
    ("Vielfalt", "Vielfalt"),  # ohne
    ("Modelländerung", "Modelländerung"),
    ("modelländerung", "modelländerung"),
    ("Änderungsmanagement", "Änderungsmanagement"),
    ("änderungsmanagement", "änderungsmanagement"),
    ("Ergänzung", "Ergänzung"),
    ("ergänzung", "ergänzung"),
    ("Ergänzungen", "Ergänzungen"),
    ("ergänzungen", "ergänzungen"),
    ("Schließlich", "Schließlich"),
    ("schließlich", "schließlich"),
    ("verschöbe", "verschöbe"),
    ("verschöben", "verschöben"),
    ("stärksten", "stärksten"),
    ("Stärksten", "Stärksten"),
    ("schwächer", "schwächer"),
    ("Schwächer", "Schwächer"),
    ("schwächen", "schwächen"),
    ("Schwächen", "Schwächen"),
    ("Aufwände", "Aufwände"),
    ("aufwände", "aufwände"),
    ("zusätzlich", "zusätzlich"),
    ("Zusätzlich", "Zusätzlich"),
    ("zusätzliche", "zusätzliche"),
    ("Zusätzliche", "Zusätzliche"),
    ("Wahrscheinlichkeit", "Wahrscheinlichkeit"),  # ohne
    ("Anwendungsfälle", "Anwendungsfälle"),
    ("anwendungsfälle", "anwendungsfälle"),
    ("Wertschöpfungsanteil", "Wertschöpfungsanteil"),
    ("Bewährungsprobe", "Bewährungsprobe"),
    ("Eröffnung", "Eröffnung"),
    ("Veröffentlichung", "Veröffentlichung"),
    ("veröffentlich", "veröffentlich"),
    ("Veröffentlich", "Veröffentlich"),
    ("Überblick", "Überblick"),
    ("überblick", "überblick"),
    ("Bemühungen", "Bemühungen"),
    ("bemüh", "bemüh"),
    ("Bemüh", "Bemüh"),
    ("verständlich", "verständlich"),
    ("Verständlich", "Verständlich"),
    ("unmissverständlich", "unmissverständlich"),
    ("Unmissverständlich", "Unmissverständlich"),
    ("missverständlich", "missverständlich"),
    ("Missverständlich", "Missverständlich"),
    ("missverständnis", "missverständnis"),
    ("Missverständnis", "Missverständnis"),
    ("Auswählbar", "Auswählbar"),
    ("auswählbar", "auswählbar"),
    ("Heißt", "Heißt"),
    ("Hauptdarstellung", "Hauptdarstellung"),
    ("Knochenmark", "Knochenmark"),  # nope
    ("aussagekräftig", "aussagekräftig"),
    ("Aussagekräftig", "Aussagekräftig"),
    ("verlöschen", "verlöschen"),
    ("Vorläufig", "Vorläufig"),  # typo
]

def fix_text(text: str) -> tuple[str, int]:
    """Wendet alle Replacements an. NUR Wortgrenzen-basiert, KEINE Substring-Composites."""
    count = 0
    # Special Word Replacements + Extra Composites (alle wortbasiert)
    all_repls = SPECIAL_REPLACEMENTS + EXTRA_COMPOSITES
    sorted_repls = sorted(all_repls, key=lambda x: -len(x[0]))
    seen = set()  # Verhindere doppelte Ersetzung
    for fro, to in sorted_repls:
        if fro == to or fro in seen:
            continue
        seen.add(fro)
        pattern = r"(?<![A-Za-zäöüÄÖÜß0-9])" + re.escape(fro) + r"(?![A-Za-zäöüÄÖÜß0-9])"
        matches = re.findall(pattern, text)
        if matches:
            text = re.sub(pattern, to, text)
            count += len(matches)
    return text, count


def main():
    root = Path("C:/Users/will_/.claude/projects/01#scanen mit Claude")
    total_files = 0
    total_changes = 0

    for p in root.rglob("*"):
        if not p.is_file() or not should_process(p):
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except Exception:
            continue
        new_text, count = fix_text(text)
        if count > 0:
            p.write_text(new_text, encoding="utf-8")
            print(f"  {count:>4}x {p.relative_to(root)}")
            total_files += 1
            total_changes += count

    print()
    print(f"OK Total: {total_files} Dateien, {total_changes} Ersetzungen")


if __name__ == "__main__":
    main()
